### ISSUE TITLE
インストール後に再起動しなければ反映されない

### ISSUE THREAD

**Issue by moronaga-a** [mosapride/vscode-zenkaku#1]
### バージョン情報
- VScodeバージョン: 1.57.0
- zenkaku  v0.0.3
- OS macOS Catalina 10.15.7
- 他の拡張機能なし

### 手順
1. VScodeを起動
2. zenkakuをインストール
3. テスト用にファイル(/Users/ayaka/test.txt)を作成し、入力した

```
a a
a　a
```

4. 全角スペースの場合でも強調表示されなかった
  - <img width="81" alt="スクリーンショット 2021-06-12 17 07 23" src="https://user-images.githubusercontent.com/52645663/121769901-21ab9c00-cba1-11eb-8968-92254e166e51.png">

5. VScodeを終了して起動した
6. ファイルを開きなおした
7. 全角スペースの箇所が強調表示された
  - <img width="79" alt="スクリーンショット 2021-06-12 17 09 29" src="https://user-images.githubusercontent.com/52645663/121769907-2708e680-cba1-11eb-9b06-2e438f3d1cb6.png">

## 期待される結果 expected result
- 手順4で強調表示されるか、または再起動を促される、インストール手順に再起動が必要な旨記載してあるとわかりやすいです。

## 実際の結果 actual result
- VScodeを終了し起動し直さなければ、強調表示されなかった
- 再起動しても反映されないこともありました

**Comment by mosapride** [comment]
> 再起動しても反映されないこともありました

これは、検証できないですね。

Readmeを更新しました。

作った経緯自体適当ですみません。
↓経緯
https://teratail.com/questions/55169

**Comment by moronaga-a** [comment]
ありがとうございます。
とても便利な機能で大変助かっています。
